#!/bin/csh -f
# This script is called info
echo Hello ${LOGNAME}!
echo The hour is `date +%H`
echo "This machine is `uname -n`"
echo The calendar for this month is
cal
echo The processes you are running are:
ps -ef | grep  "^ *$LOGNAME"
echo "Thanks for coming. See you soon\!\!"
