# a makefile for "runString"

# Tools and options:
CC = g++
RM = rm -f

# Filenames:
OBJ = runString.o String.o
EXEC = runString

clean :
    $(RM) $(OBJ)

all : $(EXEC)

$(EXEC) : $(OBJ)
    $(CC) $^ -o $@

%.o : %.cpp
    $(CC) -c -o $@ $<
